/* Auto-generated by cbindgen. Do not edit manually. */

#ifndef OMOIKANE_H
#define OMOIKANE_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct RefCell_CdpSession RefCell_CdpSession;

typedef struct RefCell_Option_String RefCell_Option_String;

/**
 * Opaque browser handle for the C ABI.
 */
typedef struct OmoikaneBrowser {
  struct RefCell_CdpSession session;
  struct RefCell_Option_String last_error;
} OmoikaneBrowser;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a new browser handle.
 */
struct OmoikaneBrowser *omoikane_init(void);

/**
 * Destroys a browser handle previously created by [`omoikane_init`].
 */
void omoikane_free(struct OmoikaneBrowser *browser);

/**
 * Navigates the active page to `url`.
 */
bool omoikane_navigate(struct OmoikaneBrowser *browser, const char *url);

/**
 * Evaluates JavaScript in the current page and returns a JSON payload string.
 */
char *omoikane_evaluate(struct OmoikaneBrowser *browser, const char *expression);

/**
 * Returns the current document serialized as HTML.
 */
char *omoikane_get_content(struct OmoikaneBrowser *browser);

/**
 * Placeholder screenshot API for the stable ABI surface.
 */
char *omoikane_screenshot_png(struct OmoikaneBrowser *_browser);

/**
 * Returns the last error message for the browser handle, if any.
 */
char *omoikane_last_error(const struct OmoikaneBrowser *browser);

/**
 * Frees a string allocated by this library.
 */
void omoikane_string_free(char *value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OMOIKANE_H */
